-- CreateEnum
CREATE TYPE "Categoria" AS ENUM ('ELETRONICOS', 'MOVEIS_DECORACAO', 'ROUPAS_ACESSORIOS', 'LIVROS_MIDIA', 'ESPORTE_LAZER', 'BRINQUEDOS_INFANTIL', 'ELETRODOMESTICOS', 'INSTRUMENTOS_MUSICAIS', 'FERRAMENTAS_JARDIM', 'OUTROS');

-- AlterTable
ALTER TABLE "Item" ADD COLUMN     "categoria" "Categoria" NOT NULL DEFAULT 'OUTROS';
